"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.imageTemplateName = exports.containerName = exports.identityName = exports.storageAccountName = exports.resourceGroupName = exports.RunOutputName = exports.DistLocation = exports.DistResourceId = exports.ManagedImageLocation = exports.ReplicationRegions = exports.ImageIdForDistribute = exports.DistributeType = exports.GalleryImageId = exports.customizerDestination = exports.customizerScript = exports.customizerWindowsUpdate = exports.WindowsUpdateProvisioner = exports.InlineScript = exports.CustomizerSource = exports.sharedImageGallerySourceTypeImage = exports.managedImageSourceTypeImage = exports.platformImageSourceTypeImage = exports.marketPlaceSourceTypeImage = exports.SourceImage = exports.SourceOSType = exports.SourceImageType = exports.VMSize = exports.BuildTimeoutInMinutes = exports.NoWaitMode = exports.ImageBuilderTemplateName = exports.ResourceGroupName = exports.Location = void 0;
exports.Location = "location";
exports.ResourceGroupName = "resourceGroupName";
exports.ImageBuilderTemplateName = "imagebuilderTemplateName";
exports.NoWaitMode = "nowaitMode";
exports.BuildTimeoutInMinutes = "buildTimeoutInMinutes";
exports.VMSize = "vmProfile";
exports.SourceImageType = "sourceImageType";
exports.SourceOSType = "sourceOSType";
exports.SourceImage = "sourceImage";
exports.marketPlaceSourceTypeImage = "marketplace";
exports.platformImageSourceTypeImage = "platformimage";
exports.managedImageSourceTypeImage = "managedimage";
exports.sharedImageGallerySourceTypeImage = "sharedgalleryimage";
exports.CustomizerSource = "customizerSource";
exports.InlineScript = "inlineScript";
exports.WindowsUpdateProvisioner = "windowsUpdateProvisioner";
exports.customizerWindowsUpdate = "customizerWindowsUpdate";
exports.customizerScript = "customizerScript";
exports.customizerDestination = "customizerDestination";
exports.GalleryImageId = "galleryImageId";
exports.DistributeType = "distributorType";
exports.ImageIdForDistribute = "imageIdForDistribute";
exports.ReplicationRegions = "replicationRegions";
exports.ManagedImageLocation = "managedImageLocation";
exports.DistResourceId = "distResourceId";
exports.DistLocation = "distLocation";
exports.RunOutputName = "runOutputName";
exports.resourceGroupName = "rg_aib_action_";
exports.storageAccountName = "strgcc";
exports.identityName = "aibUserId";
exports.containerName = "imagebuilder-vststask";
exports.imageTemplateName = "imagebuilderTemplate";
