"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.imageTemplateName = exports.containerName = exports.identityName = exports.storageAccountName = exports.resourceGroupName = exports.RunOutputName = exports.DistLocation = exports.DistResourceId = exports.ManagedImageLocation = exports.ReplicationRegions = exports.ImageIdForDistribute = exports.DistributeType = exports.GalleryImageId = exports.customizerDestination = exports.customizerScript = exports.customizerWindowsUpdate = exports.WindowsUpdateProvisioner = exports.InlineScript = exports.CustomizerSource = exports.sharedImageGallerySourceTypeImage = exports.managedImageSourceTypeImage = exports.platformImageSourceTypeImage = exports.marketPlaceSourceTypeImage = exports.SourceImage = exports.SourceOSType = exports.SourceImageType = exports.ManagedIdentity = exports.VMSize = exports.BuildTimeoutInMinutes = exports.NoWaitMode = exports.ImageBuilderTemplateName = exports.ResourceGroupName = exports.Location = void 0;
exports.Location = "location";
exports.ResourceGroupName = "resource-group-name";
exports.ImageBuilderTemplateName = "image-builder-template-name";
exports.NoWaitMode = "nowaitMode";
exports.BuildTimeoutInMinutes = "buildTimeoutInMinutes";
exports.VMSize = "vm-size";
exports.ManagedIdentity = "managed-identity";
exports.SourceImageType = "source-image-type";
exports.SourceOSType = "source-os-type";
exports.SourceImage = "source-image";
exports.marketPlaceSourceTypeImage = "marketplace";
exports.platformImageSourceTypeImage = "platformimage";
exports.managedImageSourceTypeImage = "managedimage";
exports.sharedImageGallerySourceTypeImage = "SharedGalleryImage";
exports.CustomizerSource = "customizer-source";
exports.InlineScript = "inlineScript";
exports.WindowsUpdateProvisioner = "windowsUpdateProvisioner";
exports.customizerWindowsUpdate = "customizer-windows-update";
exports.customizerScript = "customizer-script";
exports.customizerDestination = "customizer-destination";
exports.GalleryImageId = "galleryImageId";
exports.DistributeType = "distributor-type";
exports.ImageIdForDistribute = "imageIdForDistribute";
exports.ReplicationRegions = "replicationRegions";
exports.ManagedImageLocation = "managed-image-location";
exports.DistResourceId = "dist-resource-id";
exports.DistLocation = "dist-location";
exports.RunOutputName = "run-output-name";
exports.resourceGroupName = "rg_aib_action_";
exports.storageAccountName = "strgacc";
exports.identityName = "aibUserId_";
exports.containerName = "imagebuilder-aib-action";
exports.imageTemplateName = "imagebuilderTemplate_";
