"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.imageTemplateName = exports.containerName = exports.storageAccountName = exports.RunOutputName = exports.DistLocation = exports.DistResourceId = exports.DistributeType = exports.customizerDestination = exports.customizerScript = exports.customizerWindowsUpdate = exports.CustomizerSource = exports.sharedImageGallerySourceTypeImage = exports.managedImageSourceTypeImage = exports.platformImageSourceTypeImage = exports.marketPlaceSourceTypeImage = exports.SourceImage = exports.SourceOSType = exports.SourceImageType = exports.VMSize = exports.BuildTimeoutInMinutes = exports.NoWaitMode = exports.ImageBuilderTemplateName = exports.ManagedIdentity = exports.ResourceGroupName = exports.Location = void 0;
exports.Location = "location";
exports.ResourceGroupName = "resource-group-name";
exports.ManagedIdentity = "managed-identity";
exports.ImageBuilderTemplateName = "image-builder-template-name";
exports.NoWaitMode = "nowait-mode";
exports.BuildTimeoutInMinutes = "build-timeout-in-minutes";
exports.VMSize = "vm-size";
exports.SourceImageType = "source-image-type";
exports.SourceOSType = "source-os-type";
exports.SourceImage = "source-image";
exports.marketPlaceSourceTypeImage = "marketplace";
exports.platformImageSourceTypeImage = "platformimage";
exports.managedImageSourceTypeImage = "managedimage";
exports.sharedImageGallerySourceTypeImage = "SharedGalleryImage";
exports.CustomizerSource = "customizer-source";
exports.customizerWindowsUpdate = "customizer-windows-update";
exports.customizerScript = "customizer-script";
exports.customizerDestination = "customizer-destination";
exports.DistributeType = "distributor-type";
exports.DistResourceId = "dist-resource-id";
exports.DistLocation = "dist-location";
exports.RunOutputName = "run-output-name";
exports.storageAccountName = "strgacc";
exports.containerName = "imagebuilder-aib-action";
exports.imageTemplateName = "imagebuilderTemplate_";
