# This is a basic workflow to help you get started with Actions
name: CI
# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
      
  job1:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    name: A job to use action to run aib action
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    
     # To use this repository's private action,
      # you must check out the repository
    - name: Checkout
      uses: actions/checkout@v2
    - shell: bash
      run: mkdir -p homework
    - shell: bash
      run: |
        echo Hellooooooooooo Hiiiiiiiiiiiii! > homework/hello-world.txt |
        echo Hiiiiiiiiiiiii! Hellooooooooooo > homework/hello-world2.txt
    #- name: Upload hello world file
     # uses: actions/upload-artifact@v1
      #with:
       # name: hello-world
        #path: homework
    #- name: Download hello world file
     # uses: actions/download-artifact@v1
      #with:
       # name: hello-world
        #path: homework
    
    - name: Login via Az module
      uses: azure/login@v1.1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}      
    
    # uses action for AIB to create image
    - name: aib action
      id: aib
      uses: ./
      with:
        location: 'westus'
        #resource-group-name: 'rg_aib_action_1597077618408'
        #resource-group-name: 'aibResourceGroupSIG'
        managed-identity: 'aibIdentitySIGLin'
        #managed-identity: 'aibIdentity2'
        resource-group-name: 'aibResourceGroupLin'
        #resource-group-name: 'aibRG2'
        #resource-group-name: 'rg_aib_action_1597591645408'
        #image-builder-template-name: 'imagetmpsigvhd11'
        #image-builder-template-name: '${{ GITHUB.WORKSPACE }}/src/sigTemplate.json'
        source-os-type: 'linux'
        source-image-type: 'SharedGalleryImage'
        #source-image: MicrosoftWindowsServer:WindowsServer:2019-Datacenter:latest
        #source-image: Canonical:UbuntuServer:18.04-DAILY-LTS:latest
        #source-image: '/subscriptions/f9b6b78c-2720-4293-9fc7-2c38fcebb2c6/resourceGroups/aibResourceGroupLin/providers/Microsoft.Compute/images/aibManagedImageLin'
        source-image: '/subscriptions/f9b6b78c-2720-4293-9fc7-2c38fcebb2c6/resourceGroups/aibResourceGroupLin/providers/Microsoft.Compute/galleries/sharedImageGalleryLin/images/imgdefnlin/versions/0.24374.10929'
        #source-image: '/subscriptions/f9b6b78c-2720-4293-9fc7-2c38fcebb2c6/resourceGroups/aibResourceGroupSIG/providers/Microsoft.Compute/galleries/sharedImageGallery/images/imgdefn/versions/0.24373.21584'
        customizer-source: '${{ GITHUB.WORKSPACE }}/homework/hello-world.txt'
        customizer-script: |
          sudo mkdir /buildArtifactvhd
          sudo cp -r /tmp/hello-world/ /buildArtifactvhd/hello-world
        distributor-type: 'VHD'
        #buildTimeoutInMinutes: '1'
        #dist-resource-id: '/subscriptions/c00d16c7-6c1f-4c03-9be1-6934a4c49682/resourceGroups/aibResourceGroup/providers/Microsoft.Compute/galleries/myaibsig01/images/winSvrimages'
        #dist-resource-id: '/subscriptions/f9b6b78c-2720-4293-9fc7-2c38fcebb2c6/resourceGroups/aibResourceGroupLin/providers/Microsoft.Compute/galleries/sharedImageGalleryLin/images/imgdefnlin'
        #dist-resource-id: '/subscriptions/f9b6b78c-2720-4293-9fc7-2c38fcebb2c6/resourceGroups/aibRG2/providers/Microsoft.Compute/galleries/sharedImageGallery2/images/imgdefn2'
        #dist-resource-id: '/subscriptions/f9b6b78c-2720-4293-9fc7-2c38fcebb2c6/resourceGroups/aibResourceGroupLin/providers/Microsoft.Compute/images/aibManagedImageLin'
        #dist-resource-id: '/subscriptions/f9b6b78c-2720-4293-9fc7-2c38fcebb2c6/resourceGroups/aibResourceGroupMGLin/providers/Microsoft.Compute/images/aibManagedImage'
        dist-location: 'westus'
    - name: print aib output
      run: echo output from aib ${{ steps.aib.outputs.imagebuilderRunStatus }} ${{ steps.aib.outputs.runOutputName }} ${{ steps.aib.outputs.customImageURI }}